# Generated by Django 3.2 on 2023-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('normalize_trackone', models.BooleanField(default=False)),
                ('normalize_tracktwo', models.BooleanField(default=False)),
            ],
        ),
    ]
