# Generated by Django 3.2 on 2023-06-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_auto_20230628_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosettings',
            name='normalize_trackone_target_dBFS',
        ),
        migrations.RemoveField(
            model_name='audiosettings',
            name='normalize_tracktwo_target_dBFS',
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='normalize_trackone_headroom',
            field=models.DecimalField(decimal_places=1, default=-12.0, max_digits=4, validators=[django.core.validators.MinValueValidator(-12.0), django.core.validators.MaxValueValidator(-6.0)]),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='normalize_tracktwo_headroom',
            field=models.DecimalField(decimal_places=1, default=-12.0, max_digits=4, validators=[django.core.validators.MinValueValidator(-12.0), django.core.validators.MaxValueValidator(-6.0)]),
        ),
    ]
