# Generated by Django 3.2 on 2023-06-28 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0003_auto_20230628_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosettings',
            name='fade_in_duration_trackone',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fade_in_duration_tracktwo',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fade_out_duration_trackone',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fade_out_duration_tracktwo',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fadein_trackone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fadein_tracktwo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fadeout_trackone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='fadeout_tracktwo',
            field=models.BooleanField(default=False),
        ),
    ]
