# Generated by Django 3.2 on 2023-06-28 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0004_auto_20230628_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_in_duration_trackone',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_in_duration_tracktwo',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_out_duration_trackone',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_out_duration_tracktwo',
            field=models.DecimalField(decimal_places=1, default=0, help_text='in milliseconds', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
