# Generated by Django 3.2 on 2023-06-28 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0007_auto_20230628_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_in_duration_trackone',
            field=models.IntegerField(default=0, help_text='in milliseconds', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_in_duration_tracktwo',
            field=models.IntegerField(default=0, help_text='in milliseconds', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_out_duration_trackone',
            field=models.IntegerField(default=0, help_text='in milliseconds', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='fade_out_duration_tracktwo',
            field=models.IntegerField(default=0, help_text='in milliseconds', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
