# Generated by Django 3.2 on 2023-06-29 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0008_auto_20230628_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosettings',
            name='min_silence_duration',
            field=models.IntegerField(default=1000, help_text='Minimum duration of silence in milliseconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='silence_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='silence_threshold',
            field=models.IntegerField(default=-40, help_text='Silence threshold in dBFS (decibels relative to full scale)', validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
