# Generated by Django 3.2 on 2023-06-30 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0009_auto_20230629_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosettings',
            name='crossfade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiosettings',
            name='crossfade_duration',
            field=models.IntegerField(default=5000, help_text='Define the duration of the crossfade in milliseconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
