# Generated by Django 3.2 on 2023-07-13 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0013_auto_20230713_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosettings',
            name='high_freq_damping_trackone',
            field=models.FloatField(default=0.5, help_text='controls the damping of high frequencies', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='high_freq_damping_tracktwo',
            field=models.FloatField(default=0.5, help_text='controls the damping of high frequencies', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='reverberance_trackone',
            field=models.FloatField(default=0.5, help_text='controls the amount of reverb', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='audiosettings',
            name='reverberance_tracktwo',
            field=models.FloatField(default=0.5, help_text='controls the amount of reverb', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
