# Generated by Django 3.2 on 2023-07-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0014_auto_20230713_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosettings',
            name='high_freq_damping_trackone',
        ),
        migrations.RemoveField(
            model_name='audiosettings',
            name='high_freq_damping_tracktwo',
        ),
        migrations.RemoveField(
            model_name='audiosettings',
            name='reverberance_trackone',
        ),
        migrations.RemoveField(
            model_name='audiosettings',
            name='reverberance_tracktwo',
        ),
    ]
